package Component.DeliverySimulation;

import java.awt.Dimension;
import java.awt.Point;

import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

/**
 * Coupled model for the Delivery System Model
 * 
 * @author Divij and Arit
 */
public class FinalModel extends ViewableDigraph {

	// Coupled Model Ports
	private static final String OUT = "out";
	private static final String START = "start";
	private static final String STOP = "stop";
	
	/**
	 * Default Constructor for the model
	 */
	public FinalModel() {
		super("Delivery Center Simulation");
		
		// Coupled models
		ViewableDigraph expFrame = new ExperimentalFrame();
		ViewableDigraph deliverySimulator = new CoupledDeliverySimulator();
		
		// Adding the models
		add(expFrame);
		add(deliverySimulator);
		
		// Adding the ports to the model
		addInport(START);
		addInport(STOP);
		addOutport(OUT);
		
		// Adding coupling from External Environment to Experimental Frame
		addCoupling(this, START, expFrame, START);
		addCoupling(this, STOP, expFrame, STOP);
		
		// Adding coupling from Experimental Frame to Coupled Model
		addCoupling(expFrame, "generator_out", deliverySimulator, "in");
		addCoupling(expFrame, "transducer_out", this, OUT);
		
		// Adding coupling from Coupled 
		addCoupling(deliverySimulator, "out", expFrame, "in");
	}
	
    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView() {
        preferredSize = new Dimension(845, 535);
        ((ViewableComponent)withName("Delivery Model")).setPreferredLocation(new Point(25, 32));
        ((ViewableComponent)withName("Experimental Frame")).setPreferredLocation(new Point(113, 404));
    }
}
